name: story_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
flutter_launcher_icons: ^0.9.2
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  sqflite: 2.0.2
  path_provider: 2.0.9
  image_picker: 0.8.4+10
  flutter_launcher_icons: 0.9.2
  flutter_native_splash: 2.0.5
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

flutter_icons: 
  android: launcher_icon
  image_path: assets/icon/icon.png
  ios: true

flutter_native_splash: 
  color: '#C0C0C0'
  image: assets/icon/icon.png
  android: true
  ios: true

